# Předmluva {.unnumbered}

Učit se R je běh na dlouhou trať. Je to cesta, která znamená mnohem větší časovou investici než zvládnutí softwaru s GUI, jako je například SPSS. Odměnou je mnohem větší flexibilita a v ruce univerzální nástroj pro zpracování dat, analýzu, vizualizaci, ale i programování a automatizaci. R je každý den využíváno nespočetným množstvím studentů, výzkumníků a dalších odborníků pro analýzu dat, ale i vytváření webových stránek a aplikací nebo psaní knih (včetně této!). Jak bylo kdysi proneseno na dnes již zapomenutém kousku internetu:

> Evelyn Hall: I would like to know how (if) I can extract some of the information from the summary of my nlme.
>
> Simon Blomberg: This is R. There is no if. Only how.
>
> ---Evelyn Hall and Simon 'Yoda' Blomberg, R-help (April 2005)

Tento text je průvodcem pro návštěvníky poprvé vstupující do světa R, který je provede základy datové analýzy od instalace všeho nezbytného softwaru, až po manipulaci a vizualizaci dat. Slouží zároveň jako podklad pro výuku kurzu [Úvod do analýzy dat v R](https://sociology-fa-cu.github.io/Uvod_do_analyzy_dat_v_R/) na katedře sociologie FF Univerzity Karlovy. Vznik tohoto textu byl podpořen [NMS Market Research](https://nms.global/cz/).

Tato kniha je licencovaná pod [Creative Commons Attribution-NonCommercial 2.0 Generic](https://creativecommons.org/licenses/by-nc/2.0/) a je možné ji volně šířit pro nekomerční účely.
